

export const  GET_FRUITS_DATA_REQUEST="GET_FRUITS_DATA_REQUEST"
export const  GET_FRUITS_DATA_SUCCESS="GET_FRUITS_DATA_SUCCESS"
export const  GET_FRUITS_DATA_FAILURE="GET_FRUITS_DATA_FAILURE"



export const  GET_VEGI_DATA_REQUEST="GET_VEGI_DATA_REQUEST"
export const  GET_VEGI_DATA_SUCCESS="GET_VEGI_DATA_SUCCESS"
export const  GET_VEGI_DATA_FAILURE="GET_VEGI_DATA_FAILURE"

